### ISSUE TITLE
Quickly add metadata via command line arguments

### ISSUE THREAD

**Issue by trvrb** [nextstrain/sacra#11]
@barneypotter24 ---

This feature of fauna was pretty critical. It was very common and convenient to set metadata for an entire FASTA file by passing in a command line argument. For example, setting author, etc... for our USVI Zika sequences that didn't have this info in the FASTA headers:

https://github.com/nextstrain/fauna/blob/master/builds/ZIKA.md#fred-hutch-sequences

Or similarly for mumps:

https://github.com/nextstrain/fauna/blob/master/builds/MUMPS.md#upload-fred-hutch-genomes

In these situations, you really don't want to bloat the config when it's just a simple addition.

I could be wrong, but I believe current sacra is missing this functionality? Is this correct? And if so, would be really good to include it.

**Comment by barneypotter24** [comment]
Sacra is missing this as a command line function, but it is possible through editing the config. This was an intentional decision because a current goal of sacra is to keep command line syntax as minimal as possible, and encourage users to implement things through editing of the config. This current way I'm trying to keep this separation is by enforcing command line arguments specific to features of `run.py`, while information that will be processed during `dataset`, `clusters`, or `unit`(s) is kept in the config to avoid the necessity of passing dictionaries both from `CONFIG` and `kwargs` through the whole system, since I think that will negatively affect long-term maintainability.

@trvrb I'm happy to chat about where we want to draw a line between command line and config implementation for features like specific file metadata and I can easily make it work in either case.

**Comment by barneypotter24** [comment]
Added in 40eaeb53b6a6e5d7727b883385ee449f3503b2c1
